version: "3.1"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    ports:
      - ${DOCKER_MYSQL_PORT}:3306

  web:
    build:
      context: .
      dockerfile: environment/local/nginx/Dockerfile
    volumes:
        - ./code:/var/www/html
    ports:
        - ${DOCKER_NGINX_PORT}:80
    links:
        - php
        
  php:
    build:
      context: .
      dockerfile: environment/local/php-fpm/Dockerfile
    volumes:
        - ./code:/var/www/html
    links:
      - mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - APP_SECRET
      - APP_ENV
